### ISSUE TITLE
Cannot read property 'Events' of undefined

### ISSUE THREAD

**Issue by Froelund** [magus/react-native-facebook-login#110]
After setting up react-native-facebook-login in my project, and running my project, I get the following error.
![simulator screen shot apr 18 2016 5 14 25 pm](https://cloud.githubusercontent.com/assets/2089088/14605297/0bb42a36-0589-11e6-800b-83a252642f15.png)

When navigating to the line mentioned in the error, I can see that `FBLoginManager` is not a property on `NativeModules` from `React`.

File `node_modules/react-native-facebook-login/index.ios.js`

```
var React = require('react-native');
var {
  View,
  StyleSheet,
  PropTypes,
  NativeModules,
  requireNativeComponent,
  NativeMethodsMixin,
  DeviceEventEmitter,
} = React;

var { FBLoginManager } = NativeModules;

var FBLogin = React.createClass({
  statics: {
    Events: FBLoginManager.Events,
  },
```

In my application, all I do to to reproduce this issue, is to import the module:
`import FBLogin from 'react-native-facebook-login';`

**Comment by Froelund** [comment]
React native version: 0.22.2

**Comment by eadz** [comment]
I have this same issue

**Comment by eadz** [comment]
Fixed this issue by following the instructions re adding RCTFBLogin.xcodeproject to libraries and linking etc.

**Comment by eadz** [comment]
https://github.com/magus/react-native-facebook-login#setup

<img width="607" alt="screen shot 2016-05-12 at 2 16 36 pm" src="https://cloud.githubusercontent.com/assets/11939/15215792/2b969368-184c-11e6-9558-6149da93dca7.png">

**Comment by chaintan17** [comment]
still not working after follow above instruction

**Comment by welllin** [comment]
I also have this problem before. And the way I managed to solve it is to rebuild the project using `react-native run-ios`.

Hope it can help.

**Comment by navels** [comment]
I'm running into this and I'm using the latest Facebook SDK instead of the one packaged with this library.  Is that a problem?  I've double and triple-checked all the "fixes" for this error and no luck.

**Comment by gviligvili** [comment]
still going on.   react ver 32.

**Comment by jsdario** [comment]
Still going on, version 0.33

**Comment by runeogod** [comment]
any solution?

**Comment by gviligvili** [comment]
@runeogod 
I had the issue,  but cant seem to reproduce it after updating dependencies.

**Comment by runeogod** [comment]
i've upgraded my project, now i have : "Cannot read property 'loginWithReadPermissions' of undefined" , any tricks ?

**Comment by gviligvili** [comment]
I didn't mean to say i updated only RN.   I updated all of my dependencies.  You dont have to do it,  I just thought maybe im outdated.  (you update dependencies with 'cnu',  google it) 

But now it seems the original problem is gone,  so lets take it from here.  If I remember clearly,  your current problem is caused by not installing the sdk and the module the right way.  If your testing on iphone, dont forget to  check you xcode version. 

Good luck.

**Comment by bennygenel** [comment]
I am having the same issue on Android. 

Followed the Android install guide. Did everything but still having the error. No problem with iOS. Same code working just fine.

```
"react-native": "0.39.2",
"react-native-facebook-login": "^1.4.0",
"react-native-fbsdk": "^0.4.0",
```

**undefined is not an object (evaluating 'FBLoginManager.Events["LoginFound"]')**

Any suggestions to solve this issue?

**Comment by lwhiteley** [comment]
that because `FBLoginManager.Events` is not actually defined for android currently

**Comment by bennygenel** [comment]
Thank you @lwhiteley. Is it documented somewhere that is only iOS compatible? If not I think it should.

**Comment by SerzN1** [comment]
Hi guys. How it works on Android?

**Comment by tannerhallman** [comment]
Still getting this issue

**Comment by smokymcbear** [comment]
I'm also getting this issue. I've checked my Xcode and that's throwing me a different error than my simulator if that helps. 

![image](https://cloud.githubusercontent.com/assets/19962586/25540845/50a7f2a4-2c01-11e7-856f-3c21fd6296e9.png)

Also, I noticed that on Facebook's Quick start for iOS, they say to also drag the `Bolts.framework` file, which wasn't in the folder provided by `react-native-facebook-login`. Not sure if this is due to changes over time to Facebook's SDK, but I just wanted to note that.

![image](https://cloud.githubusercontent.com/assets/19962586/25540964/d032da2a-2c01-11e7-9930-0616f16ce62c.png)
