### ISSUE TITLE
Already authorized after logout/login

### ISSUE THREAD

**Issue by jigarmistry** [magus/react-native-facebook-login#231]
Hello,

I have integrated this package into my application and I am doing a login using FBLogin button. When I logged in using facebook and come back to FBLogin button , its turn the logout button and that is great.

But when I logout using that button and again login using the same button click , facebook page show the already authorized. 

Is there any way to not show this already authorized because I need to login using different account after the logout.

Any help ?

**Comment by jospablos** [comment]
Hey jigarmistry,
Still have this issue? This happens because the LoginButton takes you to authorize the currently logged in FB account (on the fb app or on opened browser/web view). If you want to log-in with a different account, you will need to log-out first from wherever you logged in. I don't know if you can remove the FB account session from your app, though, so there's no way around it.

**Comment by Blutude** [comment]
@jigarmistry Did you figure this out? I am trying to login through facebook from a different account. Is there a way to remove the session from the app? @jospablos what do you mean by 'you will need to log-out first from wherever you logged in'?
