### ISSUE TITLE
Document app security changes

### ISSUE THREAD

**Issue by niftylettuce** [magus/react-native-facebook-login#44]
You have to whitelist your app in plist to get past this screen:

![screen shot 2015-12-07 at 8 00 06 pm](https://cloud.githubusercontent.com/assets/523141/11644775/20ffd220-9d1d-11e5-9d21-1276569c3173.png)

This is not documented in this repo Readme via http://stackoverflow.com/a/30732693

**Comment by niftylettuce** [comment]
Via https://github.com/facebook/react-native/issues/1563#issuecomment-110239450

**Comment by niftylettuce** [comment]
https://github.com/mjohnston/react-native-webpack-server/pull/61

**Comment by magus** [comment]
Yeah...I think the react-native project creation process will add this flag for you, which is why it's in the most recent version of the example project included in this repository.

https://github.com/magus/react-native-facebook-login/blob/master/example/ios/example/Info.plist#L63

Not sure what their long term solution here is but for now it seems adding the `NSAppTransportSecurity` key with the correct `<dict>` value is sufficient.
