### ISSUE TITLE
Could not connect to Development Server

### ISSUE THREAD

**Issue by muchychka** [magus/react-native-facebook-login#49]
Have these errors, any ideas how to solve it?

![2015-12-17_2223](https://cloud.githubusercontent.com/assets/16341737/11881017/df86a36c-a50c-11e5-8925-432759088e12.png)

**Comment by magus** [comment]
Does not seem related to this project. You should double check your info.plist file.

**Comment by sumzer** [comment]
Hi Magus,
I'm experiencing the exact problem. I've followed all instructions from README.md file and from FaceBook SDK . I'm using Xcode 7.2 and react-native v0.16.0 and react-native-facebook-login v1.0.2. 
What is your suggestion regarding info.plist file, what to check, where to start :) .
Thanks in advance.

**Comment by magus** [comment]
Does your problem occur with a fresh react-native project? You should start there with a very basic app. It's nearly impossible to help anyone without viewing your files though.

**Comment by sumzer** [comment]
Hi Magus,
thanks for advice, I've double checked all and fixed problem. Err was in plist file after all. 

best regards

**Comment by magus** [comment]
@sumzer, if you don't mind please share the specific file or changes which resolved the issue. This seems to be a common enough gotcha that I would love to have a PR to update the README instructions with it.

**Comment by sumzer** [comment]
Hi, 
I'll be glad to help.
There is 2 .plist files in my Xcode project and I followed  instructions from https://developers.facebook.com/docs/ios/getting-started#xcode from "5. Configure Xcode Project" 
There is instruction to update .plist file for project so I've edited 
FBLogin-> Info.plist and put "<key>NSAppTransportSecurity</key> ...." code instead of  FBLoginTests -> Supporting Files -> Info.plist (this was main err)

I'm attaching those 2 files. 
![pic1](https://cloud.githubusercontent.com/assets/650911/11959673/d8e57c20-a8ce-11e5-94d0-783fef128427.png)
![pic2](https://cloud.githubusercontent.com/assets/650911/11959674/d8e88d7a-a8ce-11e5-8d16-56ba3f08862c.png)

Now this works fine.

Best regards

**Comment by magus** [comment]
Thanks @sumzer, added more specific instructions on the Info.plist file to modify.
