### ISSUE TITLE
Packager dumps a huge error after installing

### ISSUE THREAD

**Issue by danielkramer** [magus/react-native-facebook-login#7]
After installing and re-running my app the packager dumps a big error that starts (too big to post): 

    Flow failed to provide parseable output:

    `{"passed":false,"errors":[{"message":[{"descr":"ActionSheetIOS\nDuplicate module provider","code":0,"path":"/Users/Daniel/Do...

**Comment by magus** [comment]
I'm not sure this is related to the react-native-facebook-login component. Try removing references to it and see if it still fails in this same way. Another thing to try would be to open the example project located with the module, in your node_modules folder, under the react-native-facebook-login folder you should find an example directory with an example project which should build and run without issue.

**Comment by danielkramer** [comment]
Hmm.  Maybe theres an issue with my react install.. but I just created a new raw project:
    react-native init AwesomeProject

Run that and it works. Then cd into AwesomeProject and run:
    npm install --save react-native-facebook-login

Which appears to work.. then I re-run the AwesomeProject (without actually attempting to use the Facebook login) and I see the same packager error.   I was able to get it working without an issue about a week ago or so when I first tried it in a test project.  Not sure what's changed.

**Comment by magus** [comment]
After installing flow I've reproduced your error, it seems Flow is identifying two versions of the react-native libraries since it exists in both your node_modules and the node_modules of my component. The easiest solution for you is to ensure your `.flowconfig` file has the following.

```
[ignore]
.*/node_modules
```

This will resolve the packager issue you're seeing. It seems other libraries include a similar pattern, ignoring the node_modules directory. I'm not sure why this isn't a default for flow.

**Comment by danielkramer** [comment]
Thanks Magus, I'll give it a try tonight.  And thanks for the project!
