### ISSUE TITLE
Android requires 'email' permission to be requested

### ISSUE THREAD

**Issue by chrisbianca** [magus/react-native-facebook-login#86]
Hi,

Is there a reason why you've enforced that the 'email' permission always needs to be requested when using Android?  

This differs from the iOS behaviour, so I have to have separate code to handle Android and iOS and also means that I need to request a permission I otherwise wouldn't be requesting.

Thanks,
Chris

**Comment by lwhiteley** [comment]
can someone here volunteer to test the mentioned PR
and see if this issue is properly resolved for Android

Please continue the conversation in the Pull Request 

https://github.com/magus/react-native-facebook-login/pull/105

[install from my fork directly to test (using github url)]

please see the updated docs on to reference changes for your issue. 
If not there please suggest it in the PR
